spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/seguros_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires}
    username: ${DB_USER:root}
    password: ${DB_PASS:zequin15}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  facturas:
    ruta-archivos: ${RUTA_ARCHIVOS:./archivos}
  correo:
    remitente-email: ${REMITENTE_EMAIL:aperez@amiun.com.ar}
    asunto-contiene: ${ASUNTO_CONTIENE:"Has recibido un nuevo comprobante"}
    buscar-ultimos: ${BUSCAR_ULTIMOS:50}
  mail:
    enabled: ${APP_MAIL_ENABLED:false}  # en dev lo apagamos

correo:
  imap:
    host: ${CORREO_IMAP_HOST:}
    port: ${CORREO_IMAP_PORT:993}
    username: ${CORREO_IMAP_USERNAME:}
    password: ${CORREO_IMAP_PASSWORD:}
    folder: ${CORREO_IMAP_FOLDER:INBOX}
